### ISSUE TITLE
Support for filename extraction

### ISSUE THREAD

**Issue by george-oakling** [janmarek/WebLoader#102]
I would like to use WebLoader together with requireJS, but I cant find a solution, how to extract the realname of generated files, WebLoader is generating the filenames on the fly during the compilation process by generate() routine. I would like to use something like this:
```php
$this->template->webLoaderJsFile = $this->webLoader->getJsFilename('default'); // default is the section's name
```

**Comment by janmarek** [comment]
```php
$compiler = $webloader->getCompiler();
$path = $compiler->getOutputDir() . '/' . $compiler->getOutputNamingConvention()->getFilename(
    $compiler->getFileCollection()->getFiles(), $compiler
);
```

It is not very straightforward but it should work I think.

**Comment by george-oakling** [comment]
Totally perfect! Thank you very much!
