### ISSUE TITLE
Zero division

### ISSUE THREAD

**Issue by lukaspijak** [janmarek/WebLoader#109]
If webloader is empty, $size['original'] can be zero.
 
https://github.com/janmarek/WebLoader/blob/master/WebLoader/Nette/Diagnostics/Panel.php#L118

FIX:
```php
return $this->size = $size + array('ratio' => $size['original'] ? ($size['combined'] / $size['original']) * 100 : 0);
```

**Comment by JanTvrdik** [comment]
https://github.com/janmarek/WebLoader/pull/106

**Comment by fprochazka** [comment]
Thank you for reporting :)
