### ISSUE TITLE
Tracy panel might be disabled by default

### ISSUE THREAD

**Issue by janedbal** [janmarek/WebLoader#111]
I'm not sure if debugger should be enabled by default for debug mode. If you use some (slow) JS minifier and process about 40 files, it may take several seconds for every request (```Panel::compute``` method will take that time). Also, you will not see this time in tracy execution time because it is rendered in shutdown function.

**Comment by janmarek** [comment]
OMG. @fprochazka Why does panel compile the sources on every request? We should use the files which are already generated.

**Comment by fprochazka** [comment]
When I was refactoring it, I didn't use it on big files so I didn't notice it compiles them :-(

**Comment by fprochazka** [comment]
@janedbal can you try this https://github.com/janmarek/WebLoader/commit/37cae8807f6cdd20ddbf8834d2c782804acd6be3, please? I think it's fixed.

**Comment by fprochazka** [comment]
I consider this fixed, please reopen if the issue persists.

**Comment by janedbal** [comment]
@fprochazka Yes, now it works as expected. Thanks
