### ISSUE TITLE
Error: Variable $files overwritten in foreach

### ISSUE THREAD

**Issue by janmarek** [janmarek/WebLoader#116]
there is a problem with new latte and this file https://github.com/janmarek/WebLoader/blob/master/WebLoader%2FNette%2FDiagnostics%2Fpanel.latte

**Comment by snowcek** [comment]
why i downloaded old panel.latte from composer ? ... pls add this to composer repositary

**Comment by lukasojd** [comment]
Commit is only branch master. It needs to be released... :-)
