### ISSUE TITLE
Incompatibility with nette 2.3

### ISSUE THREAD

**Issue by castamir** [janmarek/WebLoader#90]
```
    "prefer-stable": true,
    "require": {
        "nette/nette": "~2.2",
        "janmarek/webloader": "~2.2",
    }
```
installs nette v2.3 but webloader v2.3.0 - version without nette 2.3 compatibility patch...

```
    "prefer-stable": true,
    "require": {
        "nette/nette": "~2.2",
        "janmarek/webloader": "~2.3.1",
    }
```
will install webloader v2.3.1 with nette 2.3 compatibility patch, but it will downgrade nette to v2.2.*

**Comment by fprochazka** [comment]
I know, master has to be tagget, I will try to do it today :)

**Comment by lookyman** [comment]
:+1:

**Comment by janmarek** [comment]
which today? :)

**Comment by fprochazka** [comment]
https://github.com/janmarek/WebLoader/releases/tag/v2.4.0
