### ISSUE TITLE
Invalidation by dependencies

### ISSUE THREAD

**Issue by adawolfa** [janmarek/WebLoader#91]
As far as I know, there isn't a way to invalidate the generated CSS/JS files in case *not directly WebLoader included* file changes. Those are, for example, files loaded via `@import` while using Less or sprite images loaded trough filter I develop these days.

My suggestion is to add an interface for filters supporting the modifications checkup. Let's say there is a method like `getLastModified()` called in debug mode returing unix timestamp of last modification of all files loaded via the specified filter - in case of sprites filter, the images or included Less files (since Less filter exposes the array of included files). I can make PR, but it will take few weeks, possibly. :)

**Comment by janmarek** [comment]
there is a discussion about it here https://github.com/janmarek/WebLoader/issues/80

**Comment by janmarek** [comment]
closin
