### ISSUE TITLE
Support for Compiler::setCheckLastModified

### ISSUE THREAD

**Issue by JanTvrdik** [janmarek/WebLoader#94]
Extension should support `Compiler::setCheckLastModified` and set it by default to FALSE in production mode.

**Comment by fprochazka** [comment]
The support has been added https://github.com/janmarek/WebLoader/commit/c8765403d710b4ad0c7ef19aa90dba9683f3256b, but for BC it's staying with default `TRUE`. In 3.0 we can change that to `%debugMode%`.
