### ISSUE TITLE
Disable on console SAPI

### ISSUE THREAD

**Issue by srigi** [janmarek/WebLoader#96]
Is there any way how to disable this extension for command-line applications?
When I run simple cli nette aplication `./bin/foo.php` from the root of the project

```php
<?php
$container = require __DIR__ . '/../app/bootstrap.php';
$model = $container->getByType('App\FooModel');
```

I get error like

```
WebLoader\Nette\CompilationException: You must create a writable directory 'myproj/bin/webtemp' in myproj/vendor/janmarek/webloader/WebLoader/Nette/Extension.php:83  @  CLI: ./bin/foo.php 
```

**Comment by fprochazka** [comment]
There is currently no way to do that. And I would not like to disable it myself (because I pre-generate the cache during deployment from CLI), so it would have to be an option.

**Comment by srigi** [comment]
So I ask in other way. Is there a way to instruct webloader in cli environment to reuse `webtemp` in my `www_root`.

**Comment by srigi** [comment]
OK, I figured out this. What I need to do is hardcode path to `%wwwDir%` by myself in `app/bootstrap.php`

```php
$configurator->addParameters(['wwwDir' => __DIR__ . '/../www']);
```
