### ISSUE TITLE
support for @import

### ISSUE THREAD

**Issue by Ciki** [janmarek/WebLoader#99]
is there support for `@import` directive? let's say I have `screen.less` file containing 

```css
@import "inc/base-layout.less";
@import "inc/header.less";
```

and I only use `screen.less` with Webloader but want it to be rebuilt on change in any `@import'ed` files.

**Comment by bckp** [comment]
Not at the moment AFAIK, but someone is working on it :)

**Comment by Ciki** [comment]
Who is that someone, you? Any idea when this can come real?
Dňa 8.6.2015 13:21 používateľ "Radovan Kepák" <notifications@github.com>
napísal:

**Comment by bckp** [comment]
See #80 and #98

**Comment by Ciki** [comment]
aah thanks for the links, I overlooked them..closing as duplicate then..
